### PR TITLE
TISTUD-8764: Oracle parser es6

### PR DESCRIPTION
**Pull request by sgtcoolguy**

### CODE REVIEW

**Comment by kolipakakondal** [comment]
Let's plan to push this ASAP, I spent a couple of hours on analysing the commits made on this and required things to accomplish - looks like most of the things are already in-place and studio is able to identify ES6 syntax.

I'll work on the following things
1. Fixing the test cases - there are around 204 test cases are getting failed on this branch!
2. I could see there are couple of issues with the error markers in the studio - it doesn't show it on the appropriate line number if something wrong with the syntax
3. Studio App designer was showing errors when I switch between editor to designer and vice-versa, this is due to the old js parser which was copied and used in it's own plugin.
4. Looks like certain keywords which are used with Promise and Proxy features are not identified as keywords -  like "then", "Proxy", "Promise".
5. Found some issues with the "let" and "const" usage - studio has not shown any compilation issues but it's getting failed at the alloy compiler level.
6. Probably, we need to add ES6 class keywords to context help - like "class", constructor", "extends", "static", etc,.

 https://github.com/appcelerator/titanium_studio/pull/1078

**Comment by kolipakakondal** [comment]
@ssekhri - Can you also start with the FR on this so that we can identify the issues early.

**Comment by ssekhri** [comment]
Issues found in FR so far:
1. the error marker for any error in script is always shown on the first line. 
2. the error message shown at the error marker states "filename.js:<line:column><error message>". This message is irrespective of the name of the js file being worked on. Either remove the filename else it should be same as the file in which error is shown.
3. For the below code
`
let a=10;
console.log("Lets declare variable now");
var a=20;
`
Upon build the error is shown as follows:
`
[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Cannot read property 'file' of undefined
`
The error instead should be related to redeclaration of the variable

**Comment by kolipakakondal** [comment]
@sgtcoolguy I've added a couple of commits on this PR earlier but looks like those are overwritten with your latest changes.

- Issues related to folding js comments
- Showing the error on the correct line number
- Fixing html parser issues when js code used within the html tags
- Fixing some test cases

Probably we can merge this PR on the development branch and work on that - anyway we are targeting this for next studio release

**Comment by sgtcoolguy** [comment]
@kolipakakondal Ah, sorry about that Kondal. Yeah I can merge to development and we can iterate there. It's still obviously unstable in terms of our test suite, but it's closer to done now. Hopefully your commits are still there locally for you can can be cherry-picked over top?

**Comment by kolipakakondal** [comment]
Thanks @sgtcoolguy, I've them in local and I'll cherry-pick them, it will address few more test scenarios

**Pull request merged**
