### PR TITLE
TISTUD 9019 - Updating the JRuby lib

### PR DESCRIPTION
**Pull request by kolipakakondal**
Updated to the latest versions
From JRuby 1.6.4 to JRuby 9.1.16
From Ruby 1.8 & 1.9 to Ruby 2.5.0

Updated the ruby gems 
	a. rake - 12.3.0
	b. sources - 0.0.1 - no change here
Updated the ‘cache’ folder

Resolved a couple of compilation/API issues

### CODE REVIEW

**Comment by kolipakakondal** [comment]
Still facing the below error - not able to see why it was unable to load yaml package with the latest versions!

```
LoadError: no such file to load -- yaml
          require at org/jruby/RubyKernel.java:956
           <main> at /Users/kkolipaka/source/studio3/bundles/com.aptana.scripting/framework/ruble/i18n.rb:1
          require at org/jruby/RubyKernel.java:956
  block in (root) at /Users/kkolipaka/source/studio3/bundles/com.aptana.scripting/framework/ruble.rb:1
           <main> at /Users/kkolipaka/source/studio3/bundles/com.aptana.scripting/framework/ruble.rb:4
          require at org/jruby/RubyKernel.java:956
           <main> at /Users/kkolipaka/source/studio3/bundles/com.aptana.scripting/framework/ruble.rb:3
	   
org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- yaml
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1300)
	at com.aptana.scripting.ScriptingEngine.getInitializedScriptingContainer(ScriptingEngine.java:293)
	at com.aptana.scripting.model.ScriptLoadJob.run(ScriptLoadJob.java:76)
	at com.aptana.scripting.model.AbstractScriptRunner.run(AbstractScriptRunner.java:144)
	at com.aptana.scripting.model.AbstractScriptRunner.run(AbstractScriptRunner.java:180)
	at com.aptana.scripting.ScriptingEngine.runScript(ScriptingEngine.java:275)
	at com.aptana.scripting.ScriptingEngine.runScript(ScriptingEngine.java:243)
	at com.aptana.scripting.model.BundleManager.loadScript(BundleManager.java:2032)
	at com.aptana.scripting.model.BundleManager$BundleLoadJob.run(BundleManager.java:129)

```

**Comment by sgtcoolguy** [comment]
So there were a few large issues here:
- we should be shipping the ruby core/library that JRuby distributes in the same structure it does, not a copy of ruby 2.5/rubygems. I grabbed the distribution of JRuby 9.1.16 and basically just copied the lib folder over as is.
- we don't need to include our own version of snakeyaml, it's bundled in the ruby stdlib.
- As a result of how they bundle snake yaml, our bundle caching mechanism is broken. For now I commented it out. We'd need to serialize/deserialize the yaml through JRuby's APIs itself now, I believe. But I'm not certain we have a huge need for it. This version of JRuby seems much faster, so maybe the caching isn't as necessary. (I suppose we wouldn't know unless we fixed it and timed with/without again).

**Comment by ppedduri** [comment]
@kolipakakondal , this PR is working fine on my environment. 
image

**Comment by kolipakakondal** [comment]
Thanks @sgtcoolguy. Good to know about them.

**Pull request merged**
