### PR TITLE
Cherry picked to development

### PR DESCRIPTION
**Pull request by sgtcoolguy**
I have cherry-picked a number of the fixes we made on release so that they can be applied to development.

### CODE REVIEW

**Comment by pinnamur** [comment]
Chris, I'm planning to merge release -> development as we are slightly stabilized for all repos. But yes, if there aren't any conflicts, then they don't need to wait. 

Did you merge release -> development ? Or, cherry-picked all the recent commits ?

**Comment by sgtcoolguy** [comment]
@pinnamur  I didn't merge, I cherry-picked what I believe are all the recent commits that weren't cherry-picked before and tried to handle merge conflicts.

**Comment by sgtcoolguy** [comment]
@pinnamur I wasn't sure when the merge was going to happen. I did this because of recent fixes I made couldn't be cherry-picked over due to conflicts. So I tried to cherry-pick way back to see if I could resolve it. Feel free to disregard/close these PRs if you're going to merge everything over in full.

**Comment by pinnamur** [comment]
Closing this PR, as I need to merge the entire release branch to development.

**Pull request closed without merging**
